# Generated by Django 4.2.2 on 2023-06-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
