# Generated by Django 4.2.2 on 2023-06-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_gato_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gato',
            new_name='Estudiantes',
        ),
    ]
