# Generated by Django 4.2.2 on 2023-07-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_gato_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
