# Generated by Django 4.2.2 on 2023-07-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_estudiantes_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='apellido',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
