# Generated by Django 4.2.2 on 2023-07-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_estudiantes_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='imagen',
        ),
    ]
