# Generated by Django 4.2.2 on 2023-08-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_estudiantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes_images/'),
        ),
    ]
