# Generated by Django 4.2.2 on 2023-08-04 02:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_estudiantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
